package ru.ekhart86.views.vocabulary;

import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;
import ru.ekhart86.views.util.ComponentFactory;

import java.util.ArrayList;
import java.util.List;
@Route("adjective")
public class Adjective extends Div implements ComponentFactory {
    public Adjective() {
        add(createHeaderContentBackToThemes("vocabulary", "Прилагательные"));
        VerticalLayout verticalLayout = new VerticalLayout();
        List<WordItem> wordsList = new ArrayList<>();
        wordsList.add(new WordItem("particular", "особый, отдельный", "[pəˈtɪkjʊlə]"));
        wordsList.add(new WordItem("same", "одинаковый", "[seim]"));
        wordsList.add(new WordItem("different", "другой", "[ˈdɪfrənt]"));
        wordsList.add(new WordItem("marvelous", "чудесный", "[ˈmɑːvələs]"));
        wordsList.add(new WordItem("even", "ровный", "[ˈiːvən]"));
        wordsList.add(new WordItem("free", "свободный", "[friː]"));
        wordsList.add(new WordItem("distinct", "особый", "[dɪsˈtɪŋkt]"));
        wordsList.add(new WordItem("immediate", "немедленный", "[ɪˈmiːdɪət]"));
        wordsList.add(new WordItem("live", "живой", "[laiv]"));
        wordsList.add(new WordItem("stiff", "негнущийся / твёрдый", "[stif]"));
        wordsList.add(new WordItem("vacant", "свободный", "[ˈveɪkənt]"));
        wordsList.add(new WordItem("valid", "действительный", "[ˈvælɪd]"));
        wordsList.add(new WordItem("invalid", "недействительный", "[ˈɪnvəlid]"));
        wordsList.add(new WordItem("intense", "насыщенный / глубокий", "[in'tens]"));
        wordsList.add(new WordItem("limited", "ограниченный", "['limitid]"));
        wordsList.add(new WordItem("unlimited", "неограниченный", "[ʌnˈlɪmɪtɪd]"));
        wordsList.add(new WordItem("entire", "целый", "[ɪnˈtaɪə]"));
        wordsList.add(new WordItem("essential", "важный", "[ɪˈsenʃəl]"));
        wordsList.add(new WordItem("mobile", "подвижный", "[ˈməʊbaɪl]"));
        wordsList.add(new WordItem("immobile", "неподвижный", "[ɪˈməʊbaɪl]"));
        wordsList.add(new WordItem("total", "полный / итоговый", "[təʊtl]"));
        wordsList.add(new WordItem("compulsory", "принудительный", "[kəmˈpʌlsərɪ]"));
        wordsList.add(new WordItem("urgent", "срочный", "[ˈɜːʤənt]"));
        wordsList.add(new WordItem("large", "большой", "[lɑːʤ]"));
        wordsList.add(new WordItem("ordinary", "обычный", "[ˈɔːdnrɪ]"));
        wordsList.add(new WordItem("possible", "возможный", "[ˈpɒsəbl]"));
        wordsList.add(new WordItem("absent", "отсутствующий", "[ˈæbsənt]"));
        wordsList.add(new WordItem("available", "доступный / имеющийся в наличии", "[əˈveɪləbl]"));
        wordsList.add(new WordItem("evident", "очевидный", "[ˈevɪdənt]"));
        wordsList.add(new WordItem("ordinary", "обычный", "[ˈɔːdnrɪ]"));
        wordsList.add(new WordItem("hand-made", "сделанный вручную", "[hænd-meɪd]"));
        wordsList.add(new WordItem("special", "особенный", "[ˈspeʃəl]"));
        wordsList.add(new WordItem("valuable", "ценный", "[ˈvæljʊ(ə)b(ə)l]"));
        wordsList.add(new WordItem("minor", "незначительный", "[ˈmaɪnə]"));
        wordsList.add(new WordItem("major", "главный / основной", "[ˈmeɪʤə]"));
        wordsList.add(new WordItem("real", "настоящий / реальный", "[rɪəl]"));
        wordsList.add(new WordItem("next", "следующий", "[nekst]"));
        wordsList.add(new WordItem("only", "единственный", "[ˈəʊnlɪ]"));
        wordsList.add(new WordItem("last", "последний", "[lɑːst]"));
        wordsList.add(new WordItem("low", "низкий", "[ləʊ]"));
        wordsList.add(new WordItem("high", "высокий", "[hai]"));
        wordsList.add(new WordItem("full", "полный", "[fʊl]"));
        wordsList.add(new WordItem("empty", "пустой", "[ˈemptɪ]"));
        wordsList.add(new WordItem("worst", "худший", "[wɜːst]"));
        wordsList.add(new WordItem("best", "лучший", "[best]"));
        wordsList.add(new WordItem("splendid", "великолепный", "[ˈsplendɪd]"));
        wordsList.add(new WordItem("magnificent", "чудесный", "[mægˈnɪfɪsnt]"));
        wordsList.add(new WordItem("paper", "бумажный", "[ˈpeɪpə]"));
        wordsList.add(new WordItem("plastic", "пластиковый", "[ˈplæstɪk]"));
        wordsList.add(new WordItem("golden", "золотой", "[ˈgəʊldən]"));
        wordsList.add(new WordItem("silver", "серебрянный", "[ˈsɪlvə]"));
        wordsList.add(new WordItem("metal", "металлический", "[metl]"));
        wordsList.add(new WordItem("steel", "стальной", "[stiːl]"));
        wordsList.add(new WordItem("copper", "медный", "[ˈkɒpə]"));
        wordsList.add(new WordItem("iron", "железный", "[ˈaɪən]"));
        wordsList.add(new WordItem("wooden", "деревянный", "[]"));
        wordsList.add(new WordItem("glass", "стеклянный", "[glɑːs]"));
        wordsList.add(new WordItem("up-to-date", "современный", "[ʌp tuː deɪt]"));
        wordsList.add(new WordItem("out-of-date", "устаревший", "[aʊt ɒv deɪt]"));
        wordsList.add(new WordItem("modern", "современный", "[mɒdn]"));
        wordsList.add(new WordItem("ancient", "древний", "[ˈeɪnʃnt]"));
        wordsList.add(new WordItem("new", "новый", "[njuː]"));
        wordsList.add(new WordItem("old", "старый", "[əʊld]"));
        wordsList.add(new WordItem("flat", "плоский", "[flæt]"));
        wordsList.add(new WordItem("pointed", "заострённый", "[ˈpɔɪntɪd]"));
        wordsList.add(new WordItem("triangular", "треугольный", "[traɪˈæŋgjʊlə]"));
        wordsList.add(new WordItem("rectangular", "прямоугольный", "[rekˈtæŋgjʊlə]"));
        wordsList.add(new WordItem("oval", "овальный", "[ˈəʊvəl]"));
        wordsList.add(new WordItem("round", "круглый", "[raʊnd]"));
        wordsList.add(new WordItem("square", "квадратный", "[skweə]"));
        wordsList.add(new WordItem("short", "короткий", "[ʃɔːt]"));
        wordsList.add(new WordItem("long", "длинный", "[lɒŋ]"));
        wordsList.add(new WordItem("gigantic", "гигантский", "[ʤaɪˈgæntɪk]"));
        wordsList.add(new WordItem("massive", "массивный", "[ˈmæsɪv]"));
        wordsList.add(new WordItem("enormous", "огромный", "[ɪˈnɔːməs]"));
        wordsList.add(new WordItem("medium-sized", "среднего размера", "[ˈmiːdɪəmsaɪzd]"));
        wordsList.add(new WordItem("huge", "огромный", "[hjuːʤ]"));
        wordsList.add(new WordItem("big", "большой", "[bɪg]"));
        wordsList.add(new WordItem("small", "маленький", "[smɔːl]"));
        wordsList.add(new WordItem("squalid", "убогий", "[ˈskwɒlɪd]"));
        wordsList.add(new WordItem("stained", "запятнанный", "[steind]"));
        wordsList.add(new WordItem("filthy", "запачканный", "[ˈfɪlθɪ]"));
        wordsList.add(new WordItem("greasy", "жирный", "[ˈɡriːsi]"));
        wordsList.add(new WordItem("little", "маленький", "[lɪtl]"));
        wordsList.add(new WordItem("tiny", "крохотный", "[ˈtaɪnɪ]"));
        verticalLayout.addAndExpand(createWordTable(wordsList));
        add(verticalLayout);
    }
}
