package ru.ekhart86.views.b2wordlist;

import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;
import ru.ekhart86.views.util.ComponentFactory;
import ru.ekhart86.views.vocabulary.WordItem;

import java.util.ArrayList;
import java.util.List;

@Route("b2-part-4")
public class B2 extends Div implements ComponentFactory {

    public B2() {
        add(createHeaderContentBackToThemes("b2-vocabulary"));
        VerticalLayout verticalLayout = new VerticalLayout();
        verticalLayout.addAndExpand(createH3Header("B2 Часть 4"));
        List<WordItem> wordsList = new ArrayList<>();
        wordsList.add(new WordItem("alter", "изменять", "[ˈɔːltə]"));
        wordsList.add(new WordItem("alteration", "внесение изменений", "[ˌɔːltəˈreɪʃ(ə)n]"));
        wordsList.add(new WordItem("alterable", "изменяемый", "[ˈɔːltərəbl]"));
        wordsList.add(new WordItem("unaltered", "неизменный", "[ʌn ˈɔːltəd]"));
        wordsList.add(new WordItem("unalterable", "непреложный", "[ʌnˈɔːltərəbl]"));
        wordsList.add(new WordItem("pound", "фунт", "[paʊnd]"));
        wordsList.add(new WordItem("seat", "место, сиденье", "[siːt]"));
        wordsList.add(new WordItem("candy", "конфеты", "[ˈkændi]"));
        wordsList.add(new WordItem("meanwhile", "тем временем", "[ˈmiːnˈwaɪl]"));
        wordsList.add(new WordItem("railway", "железная дорога", "[ˈreɪlweɪ]"));
        wordsList.add(new WordItem("railroad", "железная дорога", "[ˈreɪlrəʊd]"));
        wordsList.add(new WordItem("closet", "стенной шкаф", "[ˈklɒzɪt]"));
        wordsList.add(new WordItem("violate", "нарушать", "[ˈvaɪəleɪt]"));
        wordsList.add(new WordItem("violation", "нарушение", "[ˌvaɪəˈleɪʃən]"));
        wordsList.add(new WordItem("violator", "нарушитель, преступник", "[ˈvaɪəleɪtə]"));
        wordsList.add(new WordItem("front", "перед, передний", "[frʌnt]"));
        wordsList.add(new WordItem("in front of", "перед", "[ɪnfrʌntɒv]"));
        wordsList.add(new WordItem("frontal", "передний, лобовой", "[ˈfrʌntl]"));
        wordsList.add(new WordItem("take care", "позаботиться, заняться", "[teɪkkeə]"));
        wordsList.add(new WordItem("caretaker", "смотритель", "[ˈkeəˌteɪkə]"));
        wordsList.add(new WordItem("authorities", "органы власти", "[ɔːˈθɒrɪtiz]"));
        wordsList.add(new WordItem("matter", "иметь значение, дело, вопрос", "[ˈmætə]"));
        wordsList.add(new WordItem("thank", "благодарить", "[θæŋk]"));
        wordsList.add(new WordItem("thankful", "благодарный", "[ˈθæŋkfʊl]"));
        wordsList.add(new WordItem("thankless", "неблагодарный", "[ˈθæŋklɪs]"));
        wordsList.add(new WordItem("get through", "дозвониться", "[gɛtθruː]"));
        wordsList.add(new WordItem("cup", "чашка, кружка, кубок", "[kʌp]"));
        wordsList.add(new WordItem("take off", "снять", "[teɪkɒf]"));
        wordsList.add(new WordItem("devote", "посвятить", "[dɪˈvəʊt]"));
        wordsList.add(new WordItem("devotion", "преданность", "[dɪˈvəʊʃən]"));
        wordsList.add(new WordItem("assume", "предполагать, брать на себя", "[əˈsjuːm]"));
        wordsList.add(new WordItem("assumption", "принятие", "[əˈsʌmpʃ(ə)n]"));
        wordsList.add(new WordItem("array", "ряд, порядок, массив", "[əˈreɪ]"));
        wordsList.add(new WordItem("shelter", "укрытие, убежище", "[ˈʃɛltə]"));
        wordsList.add(new WordItem("contrary", "противоположный, вопреки", "[ˈkɒntrəri]"));
        wordsList.add(new WordItem("diminish", "уменьшаться", "[dɪˈmɪnɪʃ]"));
        wordsList.add(new WordItem("diminution", "снижение, сокращение", "[ˌdɪmɪˈnjuːʃən]"));
        wordsList.add(new WordItem("offer", "предлагать, предложение", "[ˈɒfə]"));
        wordsList.add(new WordItem("set out", "разъяснять", "[sɛtaʊt]"));
        wordsList.add(new WordItem("complain", "жаловаться", "[kəmˈpleɪn]"));
        wordsList.add(new WordItem("complaint", "жалоба", "[kəmˈpleɪnt]"));
        wordsList.add(new WordItem("favor", "услуга, одолжение", "[ˈfeɪvə]"));
        wordsList.add(new WordItem("commitment", "приверженность, обязательство", "[kəˈmɪtmənt]"));
        wordsList.add(new WordItem("intervene", "вмешиваться", "[ˌɪntə(ː)ˈviːn]"));
        wordsList.add(new WordItem("intervention", "вмешательство", "[ˌɪntə(ː)ˈvɛnʃən]"));
        wordsList.add(new WordItem("error", "ошибка", "[ˈɛrə]"));
        wordsList.add(new WordItem("erroneous", "ошибочный", "[ɪˈrəʊnɪəs]"));
        wordsList.add(new WordItem("hike", "гулять, ходить в поход", "[haɪk]"));
        wordsList.add(new WordItem("hitchhike", "автостоп", "[ˈhɪʧˌhaɪk]"));
        wordsList.add(new WordItem("blink", "мерцать, мигать", "[blɪŋk]"));
        wordsList.add(new WordItem("strip", "полоса, лента", "[strɪp]"));
        wordsList.add(new WordItem("curl", "скручивать, клубиться, завиток", "[kɜːl]"));
        wordsList.add(new WordItem("curly", "кудрявый", "[ˈkɜːli]"));
        wordsList.add(new WordItem("concrete", "бетон, бетонировать", "[ˈkɒnkriːt]"));
        wordsList.add(new WordItem("fold", "сворачивать, складывать", "[fəʊld]"));
        wordsList.add(new WordItem("science", "наука", "[ˈsaɪəns]"));
        wordsList.add(new WordItem("scientific", "научный", "[ˌsaɪənˈtɪfɪk]"));
        wordsList.add(new WordItem("scientist", "ученый", "[ˈsaɪəntɪst]"));
        wordsList.add(new WordItem("contest", "соревнование, конкурс", "[ˈkɒntɛst]"));
        wordsList.add(new WordItem("contestant", "участник, конкурсант", "[kənˈtɛstənt]"));
        wordsList.add(new WordItem("bond", "связь, узы, соединение", "[bɒnd]"));
        wordsList.add(new WordItem("retreat", "отступать", "[rɪˈtriːt]"));
        wordsList.add(new WordItem("suspend", "приостановить, подвесить", "[səsˈpɛnd]"));
        wordsList.add(new WordItem("suspension", "приостановление", "[səsˈpɛnʃən]"));
        wordsList.add(new WordItem("suspense", "неопределённость", "[səsˈpɛns]"));
        wordsList.add(new WordItem("suspended", "отсроченный", "[səsˈpɛndɪd]"));
        wordsList.add(new WordItem("fry", "жарить", "[fraɪ]"));
        wordsList.add(new WordItem("domestic", "домашний", "[dəʊˈmɛstɪk]"));
        wordsList.add(new WordItem("domesticate", "приручить, одомашнить ", "[dəʊˈmɛstɪkeɪt]"));
        wordsList.add(new WordItem("ease", "лёгкость, облегчать", "[iːz]"));
        wordsList.add(new WordItem("uneasy", "тревожный", "[ʌnˈiːzi]"));
        wordsList.add(new WordItem("uneasiness", "тревожность", "[ʌnˈiːzɪnɪs]"));
        wordsList.add(new WordItem("graduate", "выпускник, выпускаться", "[ˈgrædjʊət]"));
        wordsList.add(new WordItem("undergraduate", "студент", "[ˌʌndəˈgrædjʊɪt]"));
        wordsList.add(new WordItem("graduation", "выпуск", "[ˌgrædjʊˈeɪʃən]"));
        wordsList.add(new WordItem("postgraduate", "аспирант", "[ˌpəʊstˈgrædjʊɪt]"));
        wordsList.add(new WordItem("patch", "заплатка, латать", "[pæʧ]"));
        wordsList.add(new WordItem("tire", "шина, усталость", "[ˈtaɪə]"));
        wordsList.add(new WordItem("unless", "если не", "[ənˈlɛs]"));
        wordsList.add(new WordItem("shift", "сменить, сдвинуть", "[ʃɪft]"));
        wordsList.add(new WordItem("shifty", "ловкий, изворотливый", "[ˈʃɪfti]"));
        wordsList.add(new WordItem("hood", "капот, кожух, капюшон", "[hʊd]"));
        wordsList.add(new WordItem("waste", "тратить (впустую)", "[weɪst]"));
        wordsList.add(new WordItem("wasteful", "расточительный, разорительный", "[ˈweɪstfʊl]"));
        wordsList.add(new WordItem("notice", "замечать", "[ˈnəʊtɪs]"));
        wordsList.add(new WordItem("unnoticed", "незамеченный", "[ʌnˈnəʊtɪst]"));
        wordsList.add(new WordItem("enormous", "огромный", "[ɪˈnɔːməs]"));
        wordsList.add(new WordItem("hook", "крюк, зацеплять", "[hʊk]"));
        wordsList.add(new WordItem("hooked", "крючковатый, кривой", "[hʊkt]"));
        wordsList.add(new WordItem("partisan", "приверженец, сторонник", "[ˌpɑːtɪˈzæn]"));
        wordsList.add(new WordItem("partisanship", "приверженность", "[ˌpɑːtɪˈzænʃɪp]"));
        wordsList.add(new WordItem("angry", "злой", "[ˈæŋgri]"));
        wordsList.add(new WordItem("measure", "измерять, мера", "[ˈmɛʒə]"));
        wordsList.add(new WordItem("doubt", "сомневаться, сомнение", "[daʊt]"));
        wordsList.add(new WordItem("doubtful", "сомнительный", "[ˈdaʊtfʊl]"));
        wordsList.add(new WordItem("doubtless", "несомненный", "[ˈdaʊtlɪs]"));
        wordsList.add(new WordItem("stiff", "жёсткий, негнущийся", "[stɪf]"));
        wordsList.add(new WordItem("stiffness", "жесткость", "[ˈstɪfnəs]"));
        wordsList.add(new WordItem("stiffen", "напрячься, затвердевать", "[ˈstɪfn]"));
        wordsList.add(new WordItem("preach", "проповедовать", "[priːʧ]"));
        wordsList.add(new WordItem("preacher", "проповедник", "[ˈpriːʧə]"));
        wordsList.add(new WordItem("come off", "выйти, оторваться", "[kʌmɒf]"));
        wordsList.add(new WordItem("rail", "рельс, перила", "[reɪl]"));
        wordsList.add(new WordItem("railing", "перила", "[ˈreɪlɪŋ]"));
        wordsList.add(new WordItem("derail", "сходить с рельс", "[dɪˈreɪl]"));
        wordsList.add(new WordItem("male", "мужской", "[meɪl]"));
        wordsList.add(new WordItem("female", "женский", "[ˈfiːmeɪl]"));
        wordsList.add(new WordItem("proof", "доказательство", "[pruːf]"));
        wordsList.add(new WordItem("produce", "производить", "[ˈprɒdjuːs]"));
        wordsList.add(new WordItem("producer", "производитель", "[prəˈdjuːsə]"));
        wordsList.add(new WordItem("production", "производство", "[prəˈdʌkʃən]"));
        wordsList.add(new WordItem("tag", "этикетка, ярлык", "[tæg]"));
        wordsList.add(new WordItem("subtle", "тонкий, неуловимый", "[ˈsʌtl]"));
        wordsList.add(new WordItem("subtleness", "тонкость", "[ˈsʌtlnəs]"));
        wordsList.add(new WordItem("subtlety", "тонкость, нюанс", "[ˈsʌtlti]"));
        wordsList.add(new WordItem("nurse", "медсестра, нянька", "[nɜːs]"));
        wordsList.add(new WordItem("nursing", "уход", "[ˈnɜːsɪŋ]"));
        wordsList.add(new WordItem("nursery", "Детский сад, питомник", "[ˈnɜːsəri]"));
        wordsList.add(new WordItem("soil", "почва", "[sɔɪl]"));
        wordsList.add(new WordItem("wake", "просыпаться или будить", "[weɪk]"));
        wordsList.add(new WordItem("quiet", "тихий, спокойный, тишина", "[ˈkwaɪət]"));
        wordsList.add(new WordItem("quietness", "спокойствие", "[ˈkwaɪətnɪs]"));
        wordsList.add(new WordItem("quieten", "успокаивать", "[ˈkwaɪətn]"));
        wordsList.add(new WordItem("represent", "представлять", "[ˌrɛprɪˈzɛnt]"));
        wordsList.add(new WordItem("representative", "представитель", "[ˌrɛprɪˈzɛntətɪv]"));
        wordsList.add(new WordItem("dispute", "спор, спорить", "[dɪsˈpjuːt]"));
        wordsList.add(new WordItem("disputed", "спорный", "[dɪsˈpjuːtɪd]"));
        wordsList.add(new WordItem("undisputed", "бесспорный, необсуждаемый", "[ˌʌndɪsˈpjuːtɪd]"));
        wordsList.add(new WordItem("couch", "диван", "[kaʊʧ]"));
        wordsList.add(new WordItem("trade", "торговать, торговля, торговый", "[treɪd]"));
        wordsList.add(new WordItem("trader", "торговец", "[ˈtreɪdə]"));
        wordsList.add(new WordItem("affair", "дело", "[əˈfeə]"));
        wordsList.add(new WordItem("term", "срок, период", "[tɜːm]"));
        wordsList.add(new WordItem("long-term", "долгосрочный", "[ˈlɒŋtɜːm]"));
        wordsList.add(new WordItem("short-term", "краткосрочный", "[ʃɔːt-tɜːm]"));
        wordsList.add(new WordItem("give a ride", "подвезти", "[gɪvəraɪd]"));
        wordsList.add(new WordItem("as well", "также", "[æzwɛl]"));
        wordsList.add(new WordItem("twist", "скручивать", "[twɪst]"));
        wordsList.add(new WordItem("twisted", "витой, закрученный, сплетённый ", "[ˈtwɪstɪd]"));
        wordsList.add(new WordItem("handle", "рукоятка", "[ˈhændl]"));
        wordsList.add(new WordItem("remain", "оставаться", "[rɪˈmeɪn]"));
        wordsList.add(new WordItem("take place", "происходить, бывать", "[teɪkpleɪs]"));
        wordsList.add(new WordItem("upset", "расстроенный, расстраивать", "[ʌpˈsɛt]"));
        wordsList.add(new WordItem("inspect", "проверять, осматривать", "[ɪnˈspɛkt]"));
        wordsList.add(new WordItem("inspection", "осмотр", "[ɪnˈspɛkʃən]"));
        wordsList.add(new WordItem("authorize", "дать полномочия", "[ˈɔːθəraɪz]"));
        wordsList.add(new WordItem("authorized", "уполномоченный", "[ˈɔːʌəraɪzd]"));
        wordsList.add(new WordItem("pigeon", "голубь", "[ˈpɪʤɪn]"));
        wordsList.add(new WordItem("alert", "тревога, бдительный", "[əˈlɜːt]"));
        wordsList.add(new WordItem("alertness", "настороженность", "[əˈlɜːtnəs]"));
        wordsList.add(new WordItem("on the alert", "начеку", "[ɒnðiəˈlɜːt]"));
        wordsList.add(new WordItem("increase", "увеличивать, увеличение", "[ɪnˈkriːs]"));
        wordsList.add(new WordItem("decrease", "уменьшать, уменьшение", "[diːˈkriːs]"));
        wordsList.add(new WordItem("inquire", "узнавать, интересоваться", "[ɪnˈkwaɪə]"));
        wordsList.add(new WordItem("inquiry", "запрос", "[ɪnˈkwaɪəri]"));
        wordsList.add(new WordItem("false", "ложный, неверный", "[fɔːls]"));
        wordsList.add(new WordItem("falsehood", "неправда", "[ˈfɔːlshʊd]"));
        wordsList.add(new WordItem("falseness", "фальшивость", "[ˈfɔːlsnɪs]"));
        wordsList.add(new WordItem("either", "либо, любой", "[ˈaɪðə]"));
        wordsList.add(new WordItem("echo", "эхо, отголосок", "[ˈɛkəʊ]"));
        wordsList.add(new WordItem("stack", "стопка, куча, складывать", "[stæk]"));
        wordsList.add(new WordItem("label", "метка, ярлык, метить", "[ˈleɪbl]"));
        wordsList.add(new WordItem("neither", "никто, ни один, никакой", "[ˈnaɪðə]"));
        wordsList.add(new WordItem("sale", "продажа, сбыт", "[seɪl]"));
        wordsList.add(new WordItem("resale", "перепродажа", "[ˌriːˈseɪl]"));
        wordsList.add(new WordItem("bat", "бита, летучая мышь", "[bæt]"));
        wordsList.add(new WordItem("flat", "плоский, ровный", "[flæt]"));
        wordsList.add(new WordItem("flatten", "расплющивать", "[ˈflætn]"));
        wordsList.add(new WordItem("limit", "ограничивать, ограничение", "[ˈlɪmɪt]"));
        wordsList.add(new WordItem("head off", "выйти, отправиться", "[hɛdɒf]"));
        wordsList.add(new WordItem("get off", "уходить", "[gɛtɒf]"));
        wordsList.add(new WordItem("go off", "уходить", "[gəʊɒf]"));
        wordsList.add(new WordItem("walk off", "уходить", "[wɔːkɒf]"));
        wordsList.add(new WordItem("drive off", "уехать", "[draɪvɒf]"));
        wordsList.add(new WordItem("rural", "сельский", "[ˈrʊərəl]"));
        wordsList.add(new WordItem("compel", "вынуждать, заставлять", "[kəmˈpɛl]"));
        wordsList.add(new WordItem("boost", "повышать, усиливать", "[buːst]"));
        wordsList.add(new WordItem("booster", "ускоритель, усилитель", "[ˈbuːstə]"));
        wordsList.add(new WordItem("grin", "ухмыляться, ухмылка, оскал", "[grɪn]"));
        wordsList.add(new WordItem("tremendous", "громадный, страшный", "[trɪˈmɛndəs]"));
        wordsList.add(new WordItem("pad", "подушечка пальца, лапы", "[pæd]"));
        wordsList.add(new WordItem("aaa", "aaaa", "[aaa]"));
        wordsList.add(new WordItem("aaa", "aaaa", "[aaa]"));
        wordsList.add(new WordItem("aaa", "aaaa", "[aaa]"));
        wordsList.add(new WordItem("aaa", "aaaa", "[aaa]"));
        wordsList.add(new WordItem("aaa", "aaaa", "[aaa]"));
        wordsList.add(new WordItem("aaa", "aaaa", "[aaa]"));
        wordsList.add(new WordItem("aaa", "aaaa", "[aaa]"));
        wordsList.add(new WordItem("aaa", "aaaa", "[aaa]"));
        verticalLayout.addAndExpand(createWordTable(wordsList));
        add(verticalLayout);
    }
}
