package ru.ekhart86.views.b2wordlist;

import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;
import ru.ekhart86.views.util.ComponentFactory;
import ru.ekhart86.views.vocabulary.WordItem;

import java.util.ArrayList;
import java.util.List;

@Route("b2-part-2")
public class B2PartTwo extends Div implements ComponentFactory {

    public B2PartTwo() {
        add(createHeaderContentBackToThemes("b2-vocabulary"));
        VerticalLayout verticalLayout = new VerticalLayout();
        verticalLayout.addAndExpand(createH3Header("B2 Часть 2"));
        List<WordItem> wordsList = new ArrayList<>();
        wordsList.add(new WordItem("cord", "верёвка, шнур", "[kɔːd]"));
        wordsList.add(new WordItem("vision", "зрение или видение", "[ˈvɪʒən]"));
        wordsList.add(new WordItem("visionary", "провидец, мечтатель", "[ˈvɪʒnəri]"));
        wordsList.add(new WordItem("dozen", "дюжина", "[ˈdʌzn]"));
        wordsList.add(new WordItem("several", "несколько", "[ˈsɛvrəl]"));
        wordsList.add(new WordItem("terms", "личные отношения", "[tɜːmz]"));
        wordsList.add(new WordItem("term", "термин", "[tɜːm]"));
        wordsList.add(new WordItem("generous", "великодушный, щедрый", "[ˈʤɛnərəs]"));
        wordsList.add(new WordItem("generosity", "щедрость", "[ˌʤɛnəˈrɒsɪti]"));
        wordsList.add(new WordItem("bay", "залив", "[beɪ]"));
        wordsList.add(new WordItem("duty", "обязанность, служба", "[ˈdjuːti]"));
        wordsList.add(new WordItem("dutiful", "ответственный, обязательный", "[ˈdjuːtɪfʊl]"));
        wordsList.add(new WordItem("database", "база данных", "[ˈdeɪtəˌbeɪs]"));
        wordsList.add(new WordItem("prompt", "побуждать, подстрекать", "[prɒmpt]"));
        wordsList.add(new WordItem("prompting", "побуждение, подсказка", "[prɒmptɪŋ]"));
        wordsList.add(new WordItem("observe", "наблюдать", "[əbˈzɜːv]"));
        wordsList.add(new WordItem("observation", "наблюдение", "[ˌɒbzə(ː)ˈveɪʃən]"));
        wordsList.add(new WordItem("observer", "наблюдатель", "[əbˈzɜːvə]"));
        wordsList.add(new WordItem("spill", "проливать, рассыпать", "[spɪl]"));
        wordsList.add(new WordItem("brief", "краткий", "[briːf]"));
        wordsList.add(new WordItem("neck", "шея", "[nɛk]"));
        wordsList.add(new WordItem("society", "общество", "[səˈsaɪəti]"));
        wordsList.add(new WordItem("societal", "общественный", "[səˈsaɪətl]"));
        wordsList.add(new WordItem("weak", "слабый", "[wiːk]"));
        wordsList.add(new WordItem("weakness", "слабость", "[ˈwiːknɪs]"));
        wordsList.add(new WordItem("weaken", "ослабевать", "[ˈwiːkən]"));
        wordsList.add(new WordItem("result in", "привести к", "[rɪˈzʌltɪn]"));
        wordsList.add(new WordItem("result", "результат", "[rɪˈzʌlt]"));
        wordsList.add(new WordItem("day off", "выходной", "[deɪɒf]"));
        wordsList.add(new WordItem("customs", "таможня", "[ˈkʌstəmz]"));
        wordsList.add(new WordItem("greet", "приветствовать", "[griːt]"));
        wordsList.add(new WordItem("greeting", "приветствие", "[ˈgriːtɪŋ]"));
        wordsList.add(new WordItem("edge", "край", "[ɛʤ]"));
        wordsList.add(new WordItem("edged", "окруженный, окантованный", "[ɛʤd]"));
        wordsList.add(new WordItem("edgy", "острый, раздражительный", "[ˈɛʤi]"));
        wordsList.add(new WordItem("preserve", "сохранять, беречь", "[prɪˈzɜːv]"));
        wordsList.add(new WordItem("preservation", "сохранение", "[ˌprɛzə(ː)ˈveɪʃən]"));
        wordsList.add(new WordItem("handsome", "красивый (обычно о мужчинах)", "[ˈhænsəm]"));
        wordsList.add(new WordItem("lack", "недостаток, нуждаться", "[læk]"));
        wordsList.add(new WordItem("skin", "кожа, оболочка", "[skɪn]"));
        wordsList.add(new WordItem("encourage", "поддерживать, поощрять", "[ɪnˈkʌrɪʤ]"));
        wordsList.add(new WordItem("encouragement", "поощрение", "[ɪnˈkʌrɪʤmənt]"));
        wordsList.add(new WordItem("discourage", "отговорить, демотивировать", "[dɪsˈkʌrɪʤ]"));
        wordsList.add(new WordItem("discouragement", "упадок духа, обескураженность", "[dɪsˈkʌrɪʤmənt]"));
        wordsList.add(new WordItem("harass", "беспокоить, тревожить, изводить", "[ˈhærəs]"));
        wordsList.add(new WordItem("harassment", "домогательство", "[ˈhærəsmənt]"));
        wordsList.add(new WordItem("task", "задание, задача", "[tɑːsk]"));
        wordsList.add(new WordItem("aid", "помощь, помогать", "[eɪd]"));
        wordsList.add(new WordItem("aiding", "вспомогательный", "[ˈeɪdɪŋ]"));
        wordsList.add(new WordItem("boil", "кипеть, кипятить, варить", "[bɔɪl]"));
        wordsList.add(new WordItem("boiler", "котел", "[ˈbɔɪlə]"));
        wordsList.add(new WordItem("adventure", "приключение", "[ədˈvɛnʧə]"));
        wordsList.add(new WordItem("adventurer", "авантюрист", "[ədˈvɛnʧərə]"));
        wordsList.add(new WordItem("adventurous", "авантюрный", "[ədˈvɛnʧərəs]"));
        wordsList.add(new WordItem("weave", "плести, ткать", "[wiːv]"));
        wordsList.add(new WordItem("flavor", "аромат, вкус, приправлять", "[ˈfleɪvə]"));
        wordsList.add(new WordItem("remove", "убрать, удалить", "[rɪˈmuːv]"));
        wordsList.add(new WordItem("removal", "удаление", "[rɪˈmuːvəl]"));
        wordsList.add(new WordItem("shadow", "тень", "[ˈʃædəʊ]"));
        wordsList.add(new WordItem("shadowy", "тёмный, смутный", "[ˈʃædəʊi]"));
        wordsList.add(new WordItem("suburb", "пригород", "[ˈsʌbɜːb]"));
        wordsList.add(new WordItem("suburban", "пригородный", "[səˈbɜːbən]"));
        wordsList.add(new WordItem("complex", "сложный", "[ˈkɒmplɛks]"));
        wordsList.add(new WordItem("complexity", "сложность", "[kəmˈplɛksɪti]"));
        wordsList.add(new WordItem("birth", "рождение", "[bɜːθ]"));
        wordsList.add(new WordItem("birthday", "день рождения", "[ˈbɜːθdeɪ]"));
        wordsList.add(new WordItem("exploit", "использовать, эксплуатировать", "[ˈɛksplɔɪt]"));
        wordsList.add(new WordItem("exploitation", "использование, эксплуатация", "[ˌɛksplɔɪˈteɪʃən]"));
        wordsList.add(new WordItem("exploiter", "эксплуататор", "[ɪksˈplɔɪtə]"));
        wordsList.add(new WordItem("contain", "содержать", "[kənˈteɪn]"));
        wordsList.add(new WordItem("containment", "сдерживание", "[kənˈteɪnmənt]"));
        wordsList.add(new WordItem("bargain", "сделка, торговаться", "[ˈbɑːgɪn]"));
        wordsList.add(new WordItem("tool", "инструмент", "[tuːl]"));
        wordsList.add(new WordItem("agenda", "повестка дня", "[əˈʤendə]"));
        wordsList.add(new WordItem("ancestor", "предок", "[ˈænsɪstə]"));
        wordsList.add(new WordItem("ancestral", "наследственный, родовой", "[ænˈsɛstrəl]"));
        wordsList.add(new WordItem("missile", "ракета", "[ˈmɪsaɪl]"));
        wordsList.add(new WordItem("elaborate", "разработать, проработанный", "[ɪˈlæbərɪt]"));
        wordsList.add(new WordItem("elaboration", "разработка", "[ɪˌlæbəˈreɪʃən]"));
        wordsList.add(new WordItem("pool", "бассейн", "[puːl]"));
        wordsList.add(new WordItem("substitute", "заменять", "[ˈsʌbstɪtjuːt]"));
        wordsList.add(new WordItem("substitution", "замена", "[ˌsʌbstɪˈtjuːʃən]"));
        wordsList.add(new WordItem("lone", "одинокий", "[ləʊn]"));
        wordsList.add(new WordItem("lonely", "одинокий", "[ˈləʊnli]"));
        wordsList.add(new WordItem("loneliness", "одиночество", "[ˈləʊnlɪnəs]"));
        wordsList.add(new WordItem("lonesome", "унылый", "[ˈləʊnsəm]"));
        wordsList.add(new WordItem("amaze", "поражать, изумлять", "[əˈmeɪz]"));
        wordsList.add(new WordItem("amazement", "изумление", "[əˈmeɪzmənt]"));
        wordsList.add(new WordItem("blonde", "блондинка", "[blɒnd]"));
        wordsList.add(new WordItem("blond", "блондин", "[blɒnd]"));
        wordsList.add(new WordItem("fascinate", "очаровывать", "[ˈfæsɪneɪt]"));
        wordsList.add(new WordItem("fascination", "очарование", "[ˌfæsɪˈneɪʃən]"));
        wordsList.add(new WordItem("fascinating", "очаровательный", "[ˈfæsɪneɪtɪŋ]"));
        wordsList.add(new WordItem("violent", "яростный, жестокий", "[ˈvaɪələnt]"));
        wordsList.add(new WordItem("violence", "насилие", "[ˈvaɪələns]"));
        wordsList.add(new WordItem("relief", "облегчение, рельеф", "[rɪˈliːf]"));
        wordsList.add(new WordItem("exclude", "исключать", "[ɪksˈkluːd]"));
        wordsList.add(new WordItem("exclusion", "исключение", "[ɪksˈkluːʒən]"));
        wordsList.add(new WordItem("exclusive", "исключительный", "[ɪksˈkluːsɪv]"));
        wordsList.add(new WordItem("visible", "видимый", "[ˈvɪzəbl]"));
        wordsList.add(new WordItem("invisible", "невидимый", "[ɪnˈvɪzəbl]"));
        wordsList.add(new WordItem("visibility", "видимость", "[ˌvɪzɪˈbɪlɪti]"));
        wordsList.add(new WordItem("invisibility", "невидимость", "[ɪnˌvɪzəˈbɪlɪti]"));
        wordsList.add(new WordItem("roll", "рулон, клубок, свиток", "[rəʊl]"));
        wordsList.add(new WordItem("carry out", "выполнить", "[ˈkæriaʊt]"));
        wordsList.add(new WordItem("rape", "насиловать, изнасилование", "[reɪp]"));
        wordsList.add(new WordItem("rapist", "насильник", "[ˈreɪpɪst]"));
        wordsList.add(new WordItem("manual", "руководство, учебник", "[ˈmænjʊəl]"));
        wordsList.add(new WordItem("honor", "честь, чтить", "[ˈɒnə]"));
        wordsList.add(new WordItem("honorary", "почётный", "[ˈɒnərəri]"));
        wordsList.add(new WordItem("honorable", "почётный", "[ˈɒnərəbl]"));
        wordsList.add(new WordItem("miss", "скучать", "[mɪs]"));
        wordsList.add(new WordItem("oil", "масло", "[ɔɪl]"));
        wordsList.add(new WordItem("oily", "маслянистый", "[ˈɔɪli]"));
        wordsList.add(new WordItem("field", "поле, область", "[fiːld]"));
        wordsList.add(new WordItem("render", "оказывать, делать, отображать", "[ˈrɛndə]"));
        wordsList.add(new WordItem("accelerate", "ускорять", "[əkˈsɛləreɪt]"));
        wordsList.add(new WordItem("acceleration", "ускорение", "[əkˌsɛləˈreɪʃ(ə)n]"));
        wordsList.add(new WordItem("poke", "совать, тыкать", "[pəʊk]"));
        wordsList.add(new WordItem("steel", "сталь, стальной", "[stiːl]"));
        wordsList.add(new WordItem("bring", "принести", "[brɪŋ]"));
        wordsList.add(new WordItem("unit", "единица, элемент", "[ˈjuːnɪt]"));
        wordsList.add(new WordItem("penalty", "наказание, штраф", "[ˈpɛnlti]"));
        wordsList.add(new WordItem("matter", "иметь значение, материя", "[ˈmætə]"));
        wordsList.add(new WordItem("conclude", "заключать, завершать", "[kənˈkluːd]"));
        wordsList.add(new WordItem("conclusion", "заключение, вывод", "[kənˈkluːʒən]"));
        wordsList.add(new WordItem("conclusive", "заключительный, решающий", "[kənˈkluːsɪv]"));
        wordsList.add(new WordItem("put.. down to.. ", "объяснить, списать на", "[pʊt..daʊntuː]]"));
        wordsList.add(new WordItem("overnight", "ночной, с ночёвкой", "[ˌəʊvəˈnaɪt]"));
        wordsList.add(new WordItem("poverty", "бедность, нищета", "[ˈpɒvəti]"));
        wordsList.add(new WordItem("impoverish", "обеднять", "[ɪmˈpɒvərɪʃ]"));
        wordsList.add(new WordItem("declare", "объявлять", "[dɪˈkleə]"));
        wordsList.add(new WordItem("declaration", "объявление", "[ˌdɛkləˈreɪʃən]"));
        wordsList.add(new WordItem("period", "период, точка (в предложении)", "[ˈpɪərɪəd]"));
        wordsList.add(new WordItem("race", "раса", "[reɪs]"));
        wordsList.add(new WordItem("racial", "расовый", "[ˈreɪʃəl]"));
        wordsList.add(new WordItem("lead", "вести", "[liːd]"));
        wordsList.add(new WordItem("condition", "условие", "[kənˈdɪʃən]"));
        wordsList.add(new WordItem("conditional", "условный", "[kənˈdɪʃənl]"));
        wordsList.add(new WordItem("unconditional", "безусловный", "[ˌʌnkənˈdɪʃənl]"));
        wordsList.add(new WordItem("bar", "брусок, прут, стержень, полоса", "[bɑː]"));
        wordsList.add(new WordItem("bars", "решётка (напр. в тюрьме)", "[bɑːz]"));
        wordsList.add(new WordItem("squeeze", "сжимать", "[skwiːz]"));
        wordsList.add(new WordItem("cite", "упоминать, цитировать", "[saɪt]"));
        wordsList.add(new WordItem("citation", "цитата", "[saɪˈteɪʃən]"));
        wordsList.add(new WordItem("annual", "ежегодный", "[ˈænjʊəl]"));
        wordsList.add(new WordItem("bow", "бант, лук", "[baʊ]"));
        wordsList.add(new WordItem("butterfly", "бабочка", "[ˈbʌtəflaɪ]"));
        wordsList.add(new WordItem("punish", "наказывать", "[ˈpʌnɪʃ]"));
        wordsList.add(new WordItem("punishable", "наказуемый", "[ˈpʌnɪʃəbl]"));
        wordsList.add(new WordItem("punishment", "наказание", "[ˈpʌnɪʃmənt]"));
        wordsList.add(new WordItem("unpunished", "безнаказанный", "[ʌnˈpʌnɪʃt]"));
        wordsList.add(new WordItem("punitive", "карательный", "[ˈpjuːnɪtɪv]"));
        wordsList.add(new WordItem("purple", "пурпурный, фиолетовый", "[ˈpɜːpl]"));
        wordsList.add(new WordItem("handful", "горсть", "[ˈhændfʊl]"));
        wordsList.add(new WordItem("armful", "охапка", "[ˈɑːmfʊl]"));
        wordsList.add(new WordItem("mouthful", "полный рот", "[ˈmaʊθfʊl]"));
        wordsList.add(new WordItem("mouth", "рот", "[maʊθ]"));
        wordsList.add(new WordItem("witness", "свидетель", "[ˈwɪtnɪs]"));
        wordsList.add(new WordItem("grade", "оценка, сорт", "[greɪd]"));
        wordsList.add(new WordItem("pipe", "труба, трубка", "[paɪp]"));
        wordsList.add(new WordItem("restrain", "ограничивать, удерживать", "[rɪsˈtreɪn]"));
        wordsList.add(new WordItem("restraint", "сдержанность", "[rɪsˈtreɪnt]"));
        wordsList.add(new WordItem("unrestrained", "несдержанный", "[ˌʌnrɪsˈtreɪnd]"));
        wordsList.add(new WordItem("constrain", "ограничивать (препятствием)", "[kənˈstreɪn]"));
        wordsList.add(new WordItem("constraint", "ограничение", "[kənˈstreɪnt]"));
        wordsList.add(new WordItem("unconstrained", "непринужденный", "[ˌʌnkənˈstreɪnd]"));
        wordsList.add(new WordItem("suspect", "подозревать, подозреваемый", "[ˈsʌspɛkt]"));
        wordsList.add(new WordItem("converse", "разговаривать, беседовать", "[kənˈvɜːs]"));
        wordsList.add(new WordItem("conversation", "разговор, беседа", "[ˌkɒnvəˈseɪʃən]"));
        wordsList.add(new WordItem("liquid", "жидкость, жидкий", "[ˈlɪkwɪd]"));
        wordsList.add(new WordItem("liquidity", "текучесть, ликвидность", "[lɪˈkwɪdɪti]"));
        wordsList.add(new WordItem("resemble", "походить, напоминать", "[rɪˈzɛmbl]"));
        wordsList.add(new WordItem("resemblance", "сходство", "[rɪˈzɛmbləns]"));
        wordsList.add(new WordItem("decide", "решить", "[dɪˈsaɪd]"));
        wordsList.add(new WordItem("decision", "решение", "[dɪˈsɪʒən]"));
        wordsList.add(new WordItem("indecision", "нерешительность", "[ˌɪndɪˈsɪʒən]"));
        wordsList.add(new WordItem("bold", "смелый, отважный, жирный (шрифт)", "[bəʊld]"));
        wordsList.add(new WordItem("boldness", "смелость, дерзость", "[ˈbəʊldnəs]"));
        wordsList.add(new WordItem("case", "случай, дело, дело (уголовное)", "[keɪs]"));
        wordsList.add(new WordItem("determine", "определить", "[dɪˈtɜːmɪn]"));
        wordsList.add(new WordItem("determination", "определение", "[dɪˌtɜːmɪˈneɪʃən]"));
        wordsList.add(new WordItem("determined", "решённый, решительный", "[dɪˈtɜːmɪnd]"));
        wordsList.add(new WordItem("determinate", "решённый, определённый", "[dɪˈtɜːmɪnɪt]"));
        wordsList.add(new WordItem("undetermined", "неопределённый", "[ˌʌndɪˈtɜːmɪnd]"));
        wordsList.add(new WordItem("waste", "отходы, отбросы", "[weɪst]"));
        wordsList.add(new WordItem("wastewater", "сточные воды", "[ˈweɪstˌwɔːtə]"));
        wordsList.add(new WordItem("regard", "уважение, внимание", "[rɪˈgɑːd]"));
        wordsList.add(new WordItem("difficulty", "трудность", "[ˈdɪfɪkəlti]"));
        wordsList.add(new WordItem("ticket", "билет, талон", "[ˈtɪkɪt]"));
        wordsList.add(new WordItem("bet", "ставка, держать пари", "[bɛt]"));
        wordsList.add(new WordItem("settle", "уладить, селиться", "[ˈsɛtl]"));
        wordsList.add(new WordItem("unsettle", "расстраивать", "[ʌnˈsetl]"));
        wordsList.add(new WordItem("flow", "поток, течь", "[fləʊ]"));
        wordsList.add(new WordItem("approve", "утвердить, одобрить ", "[əˈpruːv]"));
        wordsList.add(new WordItem("approval", "утверждение", "[əˈpruːvəl]"));
        wordsList.add(new WordItem("disapprove", "не одобрять", "[ˌdɪsəˈpruːv]"));
        verticalLayout.addAndExpand(createWordTable(wordsList));
        add(verticalLayout);
    }
}
